---
- hosts: localhost
    vars:
    ansible_python_interpreter: /usr/bin/python3
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: SRG
        location: eastus
      register: rg
    - debug:
        var: rg
