- name: Create VM with defaults
  hosts: localhost
    vars:
    ansible_python_interpreter: /usr/bin/python3
  connection: local
  tasks:
   - name: Create VM
     azure_rm_virtualmachine:
      resource_group: DEMO
      name: FirstVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Pakistan@1947
      image:
       offer: CentOS
       publisher: OpenLogic
       sku: '7.3'
       version: latest
