---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating resource group - "SRG"
      azure_rm_resourcegroup:
        name: "SRG"
        location: eastus
      register: rg
    - debug:
        var: rg
