---
- hosts: localhost
  tasks:
    - name: Deleting resource group - "{{ name }}"
      azure_rm_resourcegroup:
        name: SRG
        state: absent
      register: rg
    - debug:
        var: rg
