- name: Create Azure VM
  hosts: localhost
  connection: local

  vars:
   ansible_python_interpreter: /usr/bin/python3
  tasks:

  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ az }}"
      tags:
        testing: testing
        delete: never
