- name: Stop Azure VM
  hosts: localhost
    vars:
    ansible_python_interpreter: /usr/bin/python3
  connection: local
  tasks:
    - name: Stop virtual machine
      azure_rm_virtualmachine:
        resource_group: "TestRG"
        name: "TestVM"
        allocated: no
